import React from "react";
import { useSelector } from 'react-redux';
import { Typography, Card, CardContent, Grid } from '@mui/material';
import { BarChartCustome } from "../../components/BarChartCustome/BarChartCustome";
import { PieChartCustome } from "../../components/PieChartCustome/PieChartCustome";
import { Link } from 'react-router-dom';

import styles from './HomePage.module.css';


export default function Home() {
  const { orders } = useSelector((state) => state.orders);
  const totalOrders = orders.length;
  const totalRevenue = orders.reduce((acc, order) => acc + parseFloat(order.Total.replace('$', '')), 0).toFixed(2);
  const uniqueCustomers = [...new Set(orders.map(order => order.CustomerName))];
  const totalUniqueCustomers = uniqueCustomers.length;
  const ordersPerCustomer = orders.reduce((acc, order) => {
    acc[order.CustomerName] = (acc[order.CustomerName] || 0) + 1;
    return acc;
  }, {});
  const itemQuantities = orders.flatMap(order => order.Items).reduce((acc, item) => {
    acc[item.Item] = (acc[item.Item] || 0) + parseInt(item.Quantity);
    return acc;
  }, {});
  const mostSoldItem = Object.keys(itemQuantities).length > 0
    ? Object.keys(itemQuantities).reduce((a, b) => itemQuantities[a] > itemQuantities[b] ? a : b)
    : 'No items sold';
  const revenuePerCustomer = orders.reduce((acc, order) => {
    acc[order.CustomerName] = (acc[order.CustomerName] || 0) + parseFloat(order.Total.replace('$', ''));
    return acc;
  }, {});
  const bestCustomer = Object.keys(revenuePerCustomer).length > 0
    ? Object.keys(revenuePerCustomer).reduce((a, b) => revenuePerCustomer[a] > revenuePerCustomer[b] ? a : b)
    : 'No items sold';


  const orderData = Object.entries(ordersPerCustomer).map(([customer, orders]) => ({
    customer,
    orders,
    revenue: revenuePerCustomer[customer]
  }));

  return (
    <div className={styles.container}>
      <Typography variant="h4" sx={{ mb: 2 }}>
        Order Statistics
      </Typography>
      <Grid container spacing={2}>
        <Grid item xs={12} md={4}>
          <Card variant="outlined">
            <CardContent>
              <Typography variant="h3" color="primary">
                {totalOrders}
              </Typography>
              <Typography variant="h6">Total Orders</Typography>
            </CardContent>
          </Card>
        </Grid>
        <Grid item xs={12} md={4}>
          <Card variant="outlined">
            <CardContent>
              <Typography variant="h3" color="primary">
                $ {totalRevenue}
              </Typography>
              <Typography variant="h6">Total Revenue</Typography>
            </CardContent>
          </Card>
        </Grid>
        <Grid item xs={12} md={4}>
          <Card variant="outlined">
            <CardContent>
              <Typography variant="h3" color="primary">
                {totalUniqueCustomers}
              </Typography>
              <Typography variant="h6">Unique Customers</Typography>
            </CardContent>
          </Card>
        </Grid>
        <Grid item xs={12} md={4}>
          <Card variant="outlined">
            <CardContent>
              <Typography variant="h3" color="primary"
                component={Link}
                to={`/item/${mostSoldItem}`}>
                {mostSoldItem}
              </Typography>
              <Typography variant="h6">Most Sold Item</Typography>
            </CardContent>
          </Card>
        </Grid>
        <Grid item xs={12} md={4}>
          <Card variant="outlined">
            <CardContent>
              <Typography variant="h3" color="primary"
                component={Link}
                to={`/customer/${bestCustomer}`}
                >
                {bestCustomer}
              </Typography>
              <Typography variant="h6">Best Customer</Typography>
            </CardContent>
          </Card>
        </Grid>
        <Grid item xs={12} md={4}>
          <Card variant="outlined">
            <CardContent>
              <Typography variant="h3" color="primary">
                $ {revenuePerCustomer[bestCustomer]?.toFixed(2)}
              </Typography>
              <Typography variant="h6">Revenue Generated by Best Customer</Typography>
            </CardContent>
          </Card>
        </Grid>
        <Grid item xs={12} md={8}>
          <Typography variant="h4" mt={4}>Detailed Statistics</Typography>
          <BarChartCustome  order={orderData}/>
        </Grid>
        <Grid item xs={12} md={4}>
          <Typography variant="h4" mt={4}>Detail of items by units ordered</Typography>
          <PieChartCustome items={itemQuantities} />
        </Grid>
      </Grid>
    </div>
  );
}
